[package]
name = "bitnet-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
accelerate-src = {version = "0.3.2", optional = true}
anyhow = "1.0.80"
candle-core = "0.4.0"
candle-nn = "0.4.0"
candle-transformers = "0.4.0"
clap = "4.5.1"
hf-hub = "0.3.2"
num_cpus = "1.16.0"
serde = "1.0.197"
tokenizers = "0.15.2"
tracing-chrome = "0.7.1"
tracing-subscriber = "0.3.18"

[features]
metal = ["candle-core/metal", "candle-nn/metal"]
accelerate = ["accelerate-src", "candle-core/accelerate", "candle-nn/accelerate", "candle-transformers/accelerate"]
